[phases.setup]
nixPkgs = ["nodejs", "docker"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm install dockerode",
  "npm install" 
  # Notice: 'npm run prerun' is removed from here
]

[start]
# Run the setup script right before starting the main app
cmd = "node scripts/setupImages.js && node index.js"