import { handlePortProxy } from './portProxy.js';

/**
 * Fallback middleware to handle absolute paths generated by VM apps.
 * If a request (like /_next/static/...) doesn't match any known route,
 * we check the LAST_VM_PORT cookie and try to route it to the active VM.
 */
export const handleFallbackProxy = async (req, res, next) => {
  const lastVmPort = req.cookies.LAST_VM_PORT;

  if (lastVmPort && !req.url.startsWith('/proxy/')) {
    const [vmId, port] = lastVmPort.split(':');
    
    // Inject params for handlePortProxy to use
    req.params = { ...req.params, vmId, port };
    
    console.log(`🔍 Fallback Proxy: ${req.url} -> VM ${vmId}:${port}`);
    
    return handlePortProxy(req, res, next);
  }

  next();
};
